### ISSUE TITLE
Does the app support IOS system

### ISSUE THREAD

**Issue by zhangming8** [intel-isl/OpenBot#10]
Great work.
Does the app support ios system, or is it possible to develop another app in IOS ?

**Comment by thias15** [comment]
Unfortunately, it only works with Android phones right now. However, the Android Object Detection Demo for iOS would be a good starting point to develop something similar for iOS. At the moment, it does not have the highest priority on our roadmap, but we may develop another app for iOS some time in the future.

**Comment by Pascal66** [comment]
But... Where's the the Android app ?
