### ISSUE TITLE
The Google Search Link in www.openbot.org for this github repo

### ISSUE THREAD

**Issue by jmaniac** [intel-isl/OpenBot#104]
The Link for this Github repo on the Project Site(https://www.openbot.org/) is taken from the Google Search Result redirection.

https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fintel-isl%2FOpenBot&sa=D&sntz=1&usg=AFQjCNEuy-V7lGpVZhLsVwAhzic99aPnTw

Please change it to the original link of this repo.

**Comment by thias15** [comment]
I have double-checked, but this is not the case. However, I do see what you reported on the public site. The site was built with google sites. It seems this redirect via google happens automatically, and I don't see any way to change it.
