### ISSUE TITLE
"Invalid Argument Error"

### ISSUE THREAD

**Issue by zlite** [intel-isl/OpenBot#106]
During training, I get this error (using TF 2.0.0 on Windows 10)

Train for 339.0 steps, validate for 246 steps
Epoch 1/10
  1/339 [..............................] - ETA: 52:40WARNING:tensorflow:From C:\Users\chris\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: models\my_openbot_cil_mobile_lr0.0001_bz16_bn\checkpoints\cp-0001.ckpt\assets
  1/339 [..............................] - ETA: 1:51:07
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-32-05b56d02e65c> in <module>
      5                     callbacks=[callbacks.checkpoint_cb(checkpoint_path),
      6                                callbacks.tensorboard_cb(log_path),
----> 7                                callbacks.logger_cb(log_path)])

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    518         # Lifting succeeded, so variables are initialized and we can run the
    519         # stateless function.
--> 520         return self._stateless_fn(*args, **kwds)
    521     else:
    522       canon_args, canon_kwds = \

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   1821     """Calls a graph function specialized to the inputs."""
   1822     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 1823     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   1824 
   1825   @property

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1139          if isinstance(t, (ops.Tensor,
   1140                            resource_variable_ops.BaseResourceVariable))),
-> 1141         self.captured_inputs)
   1142 
   1143   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

~\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\miniconda3\envs\openbot\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [96,256,3] and element 15 had shape [300,300,3].
	 [[node IteratorGetNext (defined at C:\Users\chris\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
  (1) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [96,256,3] and element 15 had shape [300,300,3].
	 [[node IteratorGetNext (defined at C:\Users\chris\miniconda3\envs\openbot\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
	 [[IteratorGetNext/_6]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_5273]

Function call stack:
distributed_function -> distributed_function

**Comment by thias15** [comment]
It looks like you had the Detector_V1 enabled during data collection (it processes images with a 300x300 resolution). You need to collect data with the autopilot model selected (it process images with 256x96) resolution. Check the second step in [data collection](https://github.com/intel-isl/OpenBot/tree/master/policy#data-collection).
