### ISSUE TITLE
Cannot test with "c128,128" command!

### ISSUE THREAD

**Issue by 38293312** [intel-isl/OpenBot#107]
After successfully encoding with the latest code, the OLED display is normal. I just made the most basic connection. Now I mainly test whether the 4 motors are normal. Using "Cannot test with "c128,128" command", the motor does not rotate, the serial port software The card does not change on line 10.

![QQ图片20201113153631](https://user-images.githubusercontent.com/21971730/99041931-ca235e80-25c6-11eb-9155-869013bde67a.png)
![QQ图片20201113153507](https://user-images.githubusercontent.com/21971730/99041954-d14a6c80-25c6-11eb-9185-2be10a1bc232.png)

**Comment by 38293312** [comment]
I tried both the high and low OE driven by the L298N motor, but it still couldn't rotate.

**Comment by thias15** [comment]
It looks like your Arduino is not connected to GND. You need to wire the GND pin from your Arduino to the GND of the L298N.

**Comment by thias15** [comment]
Another thing you can check is if the new line terminator is enabled in the serial monitor. By default it should be.

**Comment by 38293312** [comment]
> 您可以检查的另一件事是在串行监视器中是否启用了新的线路终止器。默认情况下应该是。

The GND and arduino GND of the L298N 12V power supply are connected together, and the test with a multimeter is OK

**Comment by 38293312** [comment]
thank you very much. The problem is solved!

**Comment by thias15** [comment]
How did you solve the problem in the end?
