### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by zlite** [intel-isl/OpenBot#111]
In the Driving Policy section, the documentation says we will find the Network folder in the following location
![Screenshot 2020-11-15 101135](https://user-images.githubusercontent.com/18071/99193048-3d45e580-272b-11eb-859a-b5c5f85d973e.png)

At least on Windows, it's actually in this location (nested deeper in the Src folder)
![Screenshot 2020-11-15 101124](https://user-images.githubusercontent.com/18071/99193056-4d5dc500-272b-11eb-9820-bb400398e26f.png)

**Comment by thias15** [comment]
Yes, good point. I usually directly drop it into the folder in Android Studio. There the `src/main` folders are skipped. I will update this in the documentation. 

Thanks!

<img src="https://user-images.githubusercontent.com/19666890/99194043-5c6d6300-277d-11eb-90d8-bb80096f1521.jpg" width="300" />
