### ISSUE TITLE
Web server for log uploading

### ISSUE THREAD

**Issue by sanyatuning** [intel-isl/OpenBot#120]
Hi @thias15!
I started working on a simple python HTTP server for log uploading.
I've added zeroconf to the server for auto-discovery if connected to the same network.
I've using Kotlin and NsdManager in the Android app.
What do you think?

**Comment by thias15** [comment]
Sounds good. But our preference would be to keep the app in Java.

**Comment by sanyatuning** [comment]
I've refactored the new classes to java and created a pull request

**Comment by thias15** [comment]
Thank you very much. I'm very busy at the moment, but will review it as soon as possible and merge.
