### ISSUE TITLE
how to connect ps3 controller to the app?

### ISSUE THREAD

**Issue by shark526** [intel-isl/OpenBot#143]
This is a awesome project, thanks to all the contributors. I have already built the car success not trying turn to the drive policy training.
I have PS3 controller but could not find any clue on how to connect to the openbot app.
Anyone have such experience on this? Appreciate for your help.

**Comment by thias15** [comment]
I'm not 100% sure about PS3 controller. But for a PS4 controller you just pair it with the phone via Bluetooth. There is also a smartphone app now. So if you have another phone you can also use that to control the bot.

**Comment by shark526** [comment]
Hi @thias15 , thanks for the reply. Yeah I know the controller app in the repo, but unfortunately I don't have another Android phone.
Connect to ps4 controller must be easier. I had use the ps3 controller connect to Android phone many years ago,  but it required rooted phone and another app.  Wondering how the ps3 controller work with openbot...

**Comment by thias15** [comment]
I don't see why the PS3 controller would be a y different from the PS4 controller. Did you try to pair?

**Comment by shark526** [comment]
> I don't see why the PS3 controller would be a y different from the PS4 controller. Did you try to pair?

yes，no Bluetooth device could be found on phone after the PS button clicked.
PS3 controller should be the tricky Bluetooth device, I remember for the root phone solution, need connect with a otg wire, use another app to detect the mac address, then pair the Bluetooth...

**Comment by thias15** [comment]
Ok, maybe it is easier to just buy a cheap knock-off BT game controller.
