### ISSUE TITLE
[Feature] Button to switch camera

### ISSUE THREAD

**Issue by Tmin10** [intel-isl/OpenBot#15]
Hello. I run the app on my phone but it display picture from front camera. After debugging I realize that I need to change https://github.com/intel-isl/OpenBot/blob/master/android/app/src/main/java/org/openbot/CameraActivity.java#L110 to 0 (LENS_FACING_FRONT) and it working fine... I don't know why front and back are reversed in my case but it could help you in future for debug the same problems.

My device is Asus Zenfone Max Pro (M2) ZB631KL, Android 9. Other cameras apps working fine.

**Comment by thias15** [comment]
We have not encountered this on any phone before. Thanks for opening this issue, we will keep an eye on it. I will close it for now, since I don't expect this to be a general issue.

**Comment by Tmin10** [comment]
Yep, thanks. Maybe in future it is possible to add camera switch into the settings.

**Comment by eagleanurag** [comment]
> 
> 
> Hello. I run the app on my phone but it display picture from front camera. After debugging I realize that I need to change https://github.com/intel-isl/OpenBot/blob/master/android/app/src/main/java/org/openbot/CameraActivity.java#L110 to 0 (LENS_FACING_FRONT) and it working fine... I don't know why front and back are reversed in my case but it could help you in future for debug the same problems.
> 
> My device is Asus Zenfone Max Pro (M2) ZB631KL, Android 9. Other cameras apps working fine.

tin my case also when i used my old Samsung J7 Max by default front camera opens

**Comment by vkuehn** [comment]
Hi I have a solution for that, can you kindly assign it to me ?
Sorry it will be not fully compliant with your naming rules..this time

**Comment by vkuehn** [comment]
is there an issue why it is a ToDo again ?
