### ISSUE TITLE
Battery Holder Wiring Colors

### ISSUE THREAD

**Issue by mikeh9** [intel-isl/OpenBot#19]
Normally the solid black wire is positive and the black wire with a white stripe is negative. The battery holder in the BOM has this convention backwards. When you hook it up, make sure you connect the solid black wire to negative (gnd) and the black and white strip to +12V. There is no fuse in the project, so if you hook it up backwards you will see some magic smoke... :-)

**Comment by thias15** [comment]
In our case the wires were red and black. Yes, with these cheap components, conventions are not always followed. It's best to verify with a multimeter.
