### ISSUE TITLE
The Policy Training Web have some problem

### ISSUE THREAD

**Issue by Twisted-Fates** [intel-isl/OpenBot#191]
I can't open this website:

`http://localhost:8000/#/uploaded`

**Comment by thias15** [comment]
Do you already have any logs uploaded? Could you provide a screenshot or error message? @sanyatuning do you have any idea?

**Comment by thias15** [comment]
Any update?

**Comment by Twisted-Fates** [comment]
![微信图片_20210512225408](https://user-images.githubusercontent.com/83832706/117996736-fc92f600-b374-11eb-9838-cedd201d3fb4.png)

**Comment by thias15** [comment]
Are you sure the Python server is running? Are you able to navigate to http://localhost:8000? Did you already record any logs on the robot that have been uploaded?

**Comment by thias15** [comment]
Please check the python output for any errors. Sometimes there are faulty datasets. If yes, delete the datasets in the uploaded folder and try again.
