### ISSUE TITLE
Tips on printing on a printer with smaller build volume?

### ISSUE THREAD

**Issue by katnoria** [intel-isl/OpenBot#2]
First of all thank you for sharing this project. 💯 

I am really excited to make one and run my on models on it.

Do you have any tips about printing on a smaller build volume? I have Ultimaker 2 extended which has a build volume of 223 mm × 223 mm × 305 mm. The body of the bot does not fit? The best I can get is this 
![image](https://user-images.githubusercontent.com/7674948/91372220-a5301280-e845-11ea-8ffb-081ef9c64646.png)

**Comment by thias15** [comment]
Hi @katnoria 

I have made a slim version of the model that fits into a 220x220 build surface. Please try it and let me know. 
If this works, I can also create a matching top cover. 

[body_bottom_slim.slt](https://github.com/intel-isl/OpenBot/blob/master/body/body_bottom_slim.stl)

<img width="981" alt="Slim Version" src="https://user-images.githubusercontent.com/19666890/91450481-a4ff3980-e87c-11ea-9325-465863919c0f.png">

**Comment by katnoria** [comment]
hi @thias15 

Thank you for making the slim version. It work 👍 
![image](https://user-images.githubusercontent.com/7674948/91526891-3c28c780-e937-11ea-871d-77d50ee17ceb.png)

Would you please create the slim version of top cover too?

**Comment by VCU-RVI-dataset** [comment]
hi @thias15

My printer is 200X200X200mm. Would you mind uploading the editable part files as well? If so, we can shrink the size or split the base and top into several pieces on our own.

**Comment by thias15** [comment]
I made a slim version for the top: [body_top_slim.stl](https://github.com/intel-isl/OpenBot/blob/master/body/body_top_slim.stl). 
<img width="1129" alt="Body_Top_Slim" src="https://user-images.githubusercontent.com/19666890/91623547-27cae600-e99c-11ea-82e5-75ac61d24820.png">

**Comment by thias15** [comment]
@VCU-RVI-dataset, I have also added the STEP files for the top and bottom of the chassis for more flexibility (see updated README). Please let me know if you figure out a good solution for smaller build volumes.

**Comment by katnoria** [comment]
Thank you @thias15
