### ISSUE TITLE
Power supply for Nano

### ISSUE THREAD

**Issue by mikeh9** [intel-isl/OpenBot#20]
Is the Nano going to be powered from the phone USB port?

The directions say to wire the speed sensors to 5V. Is this the 5V on the Nano board or the 5V on the L298N?

A wiring diagram would be helpful. :-)

**Comment by thias15** [comment]
Either works. Yes, we will eventually add a wiring diagram and step-by-step instructions with more detail.

**Comment by thias15** [comment]
I guess it is too later for you, but the wiring diagram is in the repo now. If you have any feedback let me know. Hope this helps.
