### ISSUE TITLE
only one PCB ordering w/ SMT assembly vendors?

### ISSUE THREAD

**Issue by flamby** [intel-isl/OpenBot#25]
Hello,

Are you aware of PCB vendors offering SMT assembly that accept 1 PCB order?

I tried PCBway and JLCPCB but they requires me, if i understood correctly, to order 5 PCB, with at least 2 fully assembled (SMT).

Also, I tried to see if some DIY shops sell OpenBOT kits, but did not find some for now.

To sum up, more guidance for the hardware part (PCB) would be of great help for newbie makers like me ;-)

Thanks, and keep the good works!

**Comment by thias15** [comment]
I'm not aware of vendors where you can order a single PCB. Usually this does not make sense for vendors and would cost a similar amount as ordering a larger quantity. The alternative is to follow the DIY approach where you just buy the components and connect them yourself.
