### ISSUE TITLE
FIXED: ctrlLog.txt is/was logging zeros due to (int) conversion in CameraActivity.java

### ISSUE THREAD

**Issue by chilipeppr** [intel-isl/OpenBot#30]
Hey, just a heads up to anyone else running into this, but my ctrlLog.txt was logging mostly zeros and the post-processing of the autopilot was then dropping all frames. The problem turned out to be this method.

![image](https://user-images.githubusercontent.com/7904621/93029896-99797580-f5d3-11ea-91e2-279b6e56a61d.png)

The problem is likely that across Java compilers the order of operations on line 845 and 846 is such that the author's Java compiler was converting to int after the multiplication occurred. In my compiler the (int) conversion was happening prior to the multiplication, so I was ending up with mostly zeros because the getLeft() and getRight() returns a float unless you're at full speed for which you get a 1. Those were the only lines where I got a value in ctrlLog.txt.

So, the fix is to put quotes around the multiplication step so it occurs first.

My ctrlLog.txt now looks like this:
![image](https://user-images.githubusercontent.com/7904621/93029934-dfced480-f5d3-11ea-8876-53903aab8e09.png)

It used to look almost completely like this:
![image](https://user-images.githubusercontent.com/7904621/93029941-ef4e1d80-f5d3-11ea-96a8-c7f27dae1bfc.png)

**Comment by thias15** [comment]
Thank you very much for raising this issue. This has been fixed in [dcbe88f](https://github.com/intel-isl/OpenBot/commit/dcbe88f85b6044fb86541ea303ed56e81c04f5ea)
