### ISSUE TITLE
Need Circuit Diagram 

### ISSUE THREAD

**Issue by anonymous98raj** [intel-isl/OpenBot#33]
Circuit diagram for custom pcb will be more helpful for me pls share the schematic or circuit diagram for custom pcb which you have made

**Comment by thias15** [comment]
![Schematic_IO_DRV8871_Rev2_2020-09-16_12-00-45](https://user-images.githubusercontent.com/19666890/93323058-670a8b00-f814-11ea-91a3-1952a51c5652.png)

**Comment by anonymous98raj** [comment]
thanks for the support
