### ISSUE TITLE
the slim version doesn't fit on plate 223x223

### ISSUE THREAD

**Issue by ronki2304** [intel-isl/OpenBot#41]
Hello I tried to print the slim version

but body_top_slim.stl doesn't fit

I used an ultimaker 2 which have a plate of 223*223mm

**Comment by thias15** [comment]
Did you rotate it by 45 degrees?

**Comment by ronki2304** [comment]
Yes I have rotated it 

the bottom filled  perfectely but not the top

![image](https://user-images.githubusercontent.com/25466164/93601780-fbfeb700-f9c1-11ea-9105-cdcff84f4e01.png)

I see your PR, I don't know what is the difference, but the model doesn't fit on cura

**Comment by thias15** [comment]
In the bottom left, the dimensions show as 223x223. Is there maybe some setting in Cura?

**Comment by thias15** [comment]
Any luck?

**Comment by ronki2304** [comment]
Hello sorry for my late answer,

what do you mean by some settings ???? those dimensions are the piece one on the build plate

**Comment by thias15** [comment]
Well, you have an ultimaker 2 which as a build plate of 223x223. The model is also 223x223, so it should fit. So you probably have some setting enabled which prevents you from using the complete build area. 

- Have you selected build plate adhesion with a brim or a skirt? 
This will increase the overall size of your print.
To disable it, set *Build Plate Adhesion Type* to "None". 

<img width="433" alt="Build Plate Adhesion Type" src="https://user-images.githubusercontent.com/19666890/93747224-afe88800-fbf6-11ea-9884-713af78a3fa1.png">

Other settings that are probably not necessary, but may help to fit the model:
- Disable the second extruder 
- Disable prime blob (under build plate adhesion)

**Comment by ronki2304** [comment]
Hello,
the build plate adhesion is already set to off and I don't have a second extruder,

i tried to change the g-code flavor but I don't see any change. i don't which setup has been made by @katnoria in [PR#2](https://github.com/intel-isl/OpenBot/issues/2)

**Comment by thias15** [comment]
@ronki2304 Please try https://github.com/intel-isl/OpenBot/blob/develop/body/slim_body/slim_body_top.stl from the development branch. If this does not work, checkout the glueable model.

**Comment by ronki2304** [comment]
OK it works thank you very much
