### ISSUE TITLE
有了PCB版，和组件的接线是什么样的？

### ISSUE THREAD

**Issue by 2like** [intel-isl/OpenBot#45]
@zhaoyshine 
如题，能否补充下中文版readme。

**Comment by zhaoyshine** [comment]
抱歉我按选项一来的，选项二这块我不太清楚，选项一走线我选的 杜邦线 母-母、公-母、公-公接头我各准备了十根，应该够用。目前我东西也还在路上，没有开始

**Comment by 2like** [comment]
等你选项一的好消息！
@zhaoyshine

**Comment by thias15** [comment]
Is this issue resolved?

**Comment by 2like** [comment]
> Is this issue resolved?

Can you give a detailed description of how to use PCB

**Comment by thias15** [comment]
- Attach Arduino Nano to the U1 header
- Connect motors to M1-M4
- Connect power source to Vin
- Connect sensors to the appropriate header pins

**Comment by 2like** [comment]
> 抱歉我按选项一来的，选项二这块我不太清楚，选项一走线我选的 杜邦线 母-母、公-母、公-公接头我各准备了十根，应该够用。目前我东西也还在路上，没有开始

杜邦线怎么买？搞定了吗？

**Comment by zhaoyshine** [comment]
早搞定了，杜邦线 母-母、公-母、公-公接头我各准备了十根，淘宝大把随便买。体验下来自动跟随人体识别有点不行，随便一件衣服就识别成人了，不能稳定跟某一个人，目前一直在玩手柄模式

**Comment by zhaoyshine** [comment]
这个是我demo版时拍的照片，应该是对的
![WechatIMG1](https://user-images.githubusercontent.com/30611065/95641978-41e9ff00-0ad8-11eb-8aed-1e0292929016.jpeg)
