### ISSUE TITLE
Slim model for build plates 200x200

### ISSUE THREAD

**Issue by manair** [intel-isl/OpenBot#54]
200x200 it usually an entry level for 3D printer. This project is awesome and will reach more people if we can get real slim model 😁 .  If someone has a working model for  200x200 please share. I tried working on it with blender but I am not an expert with 3D modeling. Even if the need can have it in pieces and put it back together some way it be at lease a solution.
Thanks

**Comment by thias15** [comment]
Check out the [glueable body](https://github.com/intel-isl/OpenBot/tree/master/body/cad/glue_body). It can be printed on a 150x140 build plate.
