### ISSUE TITLE
When I am training the data, it always display "There are 0 train images and 0 test images"

### ISSUE THREAD

**Issue by KevinBuddy** [intel-isl/OpenBot#57]

**Comment by thias15** [comment]
Please provide more details. What is your folder structure? How did you configure the paths in Jupyter?

**Comment by KevinBuddy** [comment]
I have copied all the txt under sensor_data and jpeg files under images into my_openbot_1

**Comment by KevinBuddy** [comment]
If I copied the whole directory into my_openbot_1,it will display an error

**Comment by KevinBuddy** [comment]
I can not find any document of associate_frames.Is that your private library？

**Comment by KevinBuddy** [comment]
Can you give me the information about associate_frames.match_frame_ctrl_cmd?

**Comment by KevinBuddy** [comment]
I got it.

**Comment by thias15** [comment]
You need to put the complete folders in the my_openbot_1 folder. The structure is train_data --> datasets --> recordings. The associate_frames.py is a python file with the utility functions for matching frames and controls.

**Comment by thias15** [comment]
> I got it.

Is the issue solved?

**Comment by KevinBuddy** [comment]
thanks, the issue is solved.
