### ISSUE TITLE
Robot

### ISSUE THREAD

**Issue by marcivrs60** [intel-isl/OpenBot#6]

**Comment by thias15** [comment]
What's the issue?

**Comment by thias15** [comment]
No description.

**Comment by marcivrs60** [comment]
thias15 <notifications@github.com> (időpont: 2020. aug. 29., Szo, 10:06)
ezt írta:

>
>
> What's the issue?
>
>

no problem.  it was all a coincidence.  i installed the github app and
suppressed something.  I'm sorry!

**Comment by thias15** [comment]
Ok, thanks. Let us know if you face any problems.
