### ISSUE TITLE
[Feature] Add automatic stopping based on ultrasonic sensor.

### ISSUE THREAD

**Issue by thias15** [intel-isl/OpenBot#66]
Add the option to the Arduino code to stop the car within some threshold of an obstacle based on the ultrasonic sensor.

**Comment by JNK88545** [comment]
void stop1(){
   ping_time = millis();
  if (distance_cm<=130){
             analogWrite(PIN_PWM1,0);
             analogWrite(PIN_PWM2,0);
             analogWrite(PIN_PWM3,0);
             analogWrite(PIN_PWM4,0);
  }
}
**Can this function be achieved by writing this way? I failed**

**Comment by thias15** [comment]
> void stop1(){
> ping_time = millis();
> if (distance_cm<=130){
> analogWrite(PIN_PWM1,0);
> analogWrite(PIN_PWM2,0);
> analogWrite(PIN_PWM3,0);
> analogWrite(PIN_PWM4,0);
> }
> }
> **Can this function be achieved by writing this way? I failed**

I just merged a PR #77 which has this feature.
