### ISSUE TITLE
[Feature] Display battery voltage and speed/rpm in the app.

### ISSUE THREAD

**Issue by thias15** [intel-isl/OpenBot#70]

**Comment by vkuehn** [comment]
I would think HUD like to waste not to much space or do you have a certain style in mind ?

**Comment by thias15** [comment]
Hi @vkuehn. Are you still planning to work on this?

**Comment by vkuehn** [comment]
@thias15 I understood there is no real demand and a refactoring planned. However if need yes I could do that.
If so It's the states of the base, So Battery level of the motor driver ?
