### ISSUE TITLE
In autopolit mode, where dose the cmd(indicator) come from?

### ISSUE THREAD

**Issue by KevinBuddy** [intel-isl/OpenBot#71]

**Comment by KevinBuddy** [comment]
It seems like that I have to control the button b and button x on the joy_stick to produce the indicator in the AUTOPOLIT mode.

**Comment by thias15** [comment]
It comes from the game controller input. It should be square (-1, left), triangle (0, straight) or circle (1, right). This is only needed if you train a conditional driving policy as shown in the project video.

**Comment by KevinBuddy** [comment]
Yes,I know.When train a conditional driving policy,I should input the button b and button x on the game controller.But I don't understand,when autopilot,the indicator will always be 0,how could it fit the training policy.

**Comment by thias15** [comment]
The high-level commands need to be provided to the policy during runtime! If there is an intersection with multiple options, the policy needs to know the intent of the user. If you are training a policy that does not need to resolve such situations, e.g. it will just drive around the kitchen block (#44), these commands are not needed.

**Comment by KevinBuddy** [comment]
Oh,I see,than you very much.
