### ISSUE TITLE
Little warning concerning hyperparameters

### ISSUE THREAD

**Issue by Pascal66** [intel-isl/OpenBot#72]
I've successfully trained just for testing my implementation, in notebook policy/policy_learning.ipynb
this took 15mn with thoses parameters of issues #31 and files  provided by @chilipeppr  
TRAIN_BATCH_SIZE = 10 #128
TEST_BATCH_SIZE = 10 #128

I think it can be usefull to warn users with "low" config, here 32Mo RAM & RTX 2060 6Go Ram
that setting batch size between 32 & 128  can cause serious problem to use their computer for a little time.

**Comment by thias15** [comment]
I believe the default in the Jupyter notebook is right now a batch size of 16. Did you try that? With this I was able to train on a (powerful) laptop using GPU and on a MacBook using CPU. The batch size of 128 requires a powerful workstation (e.g. 128 GB RAM and TitanX GPU). The 100 refers to the number of epochs. This is something else, it determines for how long to train. I will add some notes to the notebook. One option may also be to change the data loader. Right now it buffers the complete dataset if possible. Maybe it can be implemented more memory-friendly at the cost of performance.

**Comment by Pascal66** [comment]
I agree, I just explain my own experience, 
Batch of 16 is ok on a notebook, but if people put 128 to have a better train, they can be afraid about what happen 👍 
On s'amuse toujours de toute façon.

**Comment by thias15** [comment]
Disclaimer added as part of #75
