### ISSUE TITLE
Could you share the STL file of Speed Sensor gear?

### ISSUE THREAD

**Issue by aolihu** [intel-isl/OpenBot#79]
I can't find the STL file of Speed Sensor gear in the Robot Body.
Could you share it?
Thanks.

**Comment by thias15** [comment]
When we bought the speed sensors, the discs came with it. However, someone has posted about their OpenBot build on [YouMagine](https://www.youmagine.com/designs/ultimaker-2-printable-openbot-body) and has uploaded a 3D model for the encoder disc [here](https://www.youmagine.com/documents/92751/download).
