### ISSUE TITLE
OpenBot phone using front camera

### ISSUE THREAD

**Issue by NathanielChavdarov** [intel-isl/OpenBot#86]
Hey guys,

I've made my OpenBot and upon installing the app, the phone views through the front camera and not the rear camera. I tried all the buttons on my controller and look at the .ino code but I still haven't been able to find out why it's happening. Can you please help me out?

Many thanks,
Nathaniel

**Comment by thias15** [comment]
Which phone are you using? I guess you already found the solution in the open issue.
