### ISSUE TITLE
Need some training data and test data

### ISSUE THREAD

**Issue by TRLEO1** [intel-isl/OpenBot#91]
We use Python to load the tflite model and use our own data to train and test the Autopilot model, but the accuracy is very low. Could you disclose some training data and test data of the Autopilot model? We want to use them to see if there is something wrong with our data or if there is a bug in our Python code. We would appreciate it if we could get your data.

**Comment by thias15** [comment]
We cannot release our data publicly. Can you ping me on Slack so I can help you? You could also try the data in #31 by chillipeppr

**Comment by TRLEO1** [comment]
OK, thank you for your reply

**Comment by thias15** [comment]
Let me know if you need further help. Will close the issue for now.
