### ISSUE TITLE
How to connect the mobile phone and arduino nano?

### ISSUE THREAD

**Issue by 38293312** [intel-isl/OpenBot#96]
Very good project, thank you for sharing。
Use the OTG function of the mobile phone to connect to the mini USB interface of Arduino Nano?

In the future, you can consider adding new functions to the walking robot？

**Comment by 38293312** [comment]
从相关文章里面都了解到是通过OTG连接arduino nano.

**Comment by thias15** [comment]
Yes, we will add more features to OpenBot in the future. It sounds like your issue is resolved (USB OTG). I will close the issue. Please reopen and provide further details if the issue persists.
