### ISSUE TITLE
Garbled text in app

### ISSUE THREAD

**Issue by zlite** [intel-isl/OpenBot#99]
On a Pixel 4, the app shows this Chinese text when connected to OpenBot. Otherwise works normally

![Screenshot_20201109-135910](https://user-images.githubusercontent.com/18071/98601591-20756200-2294-11eb-8ac5-27407d02ad96.jpg)

**Comment by thias15** [comment]
Is your phone from China? It may be related to the Java locale.

**Comment by thias15** [comment]
I have never seen something like this. :) I believe, you are using a cheap Arduino clone with a very long Chinese product name. You can fix this by changing [line 963](https://github.com/intel-isl/OpenBot/blob/08bd925fcdbdd7eadcba8d096ab181a16ec67a1a/android/app/src/main/java/org/openbot/CameraActivity.java#L963) in CameraActivity.java to 
```
connectionSwitchCompat.setText("Connected");
```

Please let me know if that fixes your issue.

**Comment by zlite** [comment]
No, it's a standard Google Pixel 4 from the US. Running Android 11. 

Yes, it is a Chinese Arduino clone, although a very nice one (DFRobot Romeo board): https://www.dfrobot.com/romeo.html

**Comment by zlite** [comment]
That fix worked, thanks!
![Screenshot_20201109-182117](https://user-images.githubusercontent.com/18071/98619812-d5ba1100-22b8-11eb-8b45-deb596e61b5d.jpg)
